### ISSUE TITLE
broken self links behaviour with hash postfix

### ISSUE THREAD

**Issue by goshander** [gravity-ui/page-constructor#73]
https://github.com/gravity-ui/page-constructor/blob/22b49422cb389e222132034073297dc8812149b9/src/utils/url.ts#L17

hello, I can not find solution for specify hash links with anchor for the same page

ex: `https://host.com/#questions` make link with `target="_blank"`

**Comment by yuberdysheva** [comment]
Hi! Are you using locationContext? routerHostname is taken from there

**Comment by goshander** [comment]
Oh, sorry, my mistake, all works as expected
