### ISSUE TITLE
Extra slash symbol in page-constructo readme

### ISSUE THREAD

**Issue by marutkin** [gravity-ui/page-constructor#759]
When trying to run the page-constructor example code, an error was discovered in the import that breaks the build.
In https://gravity-ui.com/libraries/page-constructor#grid description import has extra slash:
``` jsx
import {Grid, Row, Col} from '@gravity-ui/page-constructor/';
```
It's be nice to have working example:
``` jsx
import {Grid, Row, Col} from '@gravity-ui/page-constructor';
```

**Comment by gorgeousvlad** [comment]
https://github.com/gravity-ui/page-constructor/pull/762
