### ISSUE TITLE
Add the feature to support theme for button in Banner block and align for image (i.e. left, center, right)

### ISSUE THREAD

**Issue by VitaliiDC8** [gravity-ui/page-constructor#787]
Image should be aligned to left/center/right, because after changing page size we want to able to user focus on specific part of image.
![image](https://github.com/gravity-ui/page-constructor/assets/127111625/ec21b01a-fe3a-40ee-a03d-0403c33176cd)
![image](https://github.com/gravity-ui/page-constructor/assets/127111625/96b74857-a445-4e52-8c2c-9c3d3d355ad7)
![image](https://github.com/gravity-ui/page-constructor/assets/127111625/bab23b7a-a58e-4e92-8937-626a4211bf69)

**Comment by stepastepastepa** [comment]
How will this be indicated in the backoffice markup? Сould there be a need to do this vertically too?

We have a MediaView: fit/fill setting in the HeaderBlock https://preview.gravity-ui.com/page-constructor/?path=/story/blocks-header--media-view-fit. Maybe this setting will be useful to you? It's not there now, but it can be reused.

**Comment by VitaliiDC8** [comment]
#794

**Comment by VitaliiDC8** [comment]
> How will this be indicated in the backoffice markup? Сould there be a need to do this vertically too? For example: top; bottom.
> 
> We have a MediaView: fit/fill setting in the HeaderBlock https://preview.gravity-ui.com/page-constructor/?path=/story/blocks-header--media-view-fit. Maybe this setting will be useful to you? It's not there now, but it can be reused.
> 
> It would be good to implement this within the same approach for similar cases.

ok, we can use MediaView like in Header block, this is acceptable for our requirments. `full `will work like it works right now. `Fit` - media content has real sizes and locates in the middle
